godfreyd/ClickHouse

docs/en/query_language/functions/string_search_functions.md

For changelog. Remove if this is non-significant change.
Category (leave one):
- New Feature
- Bug Fix
- Improvement
- Other
Description of functions positionUTF8 and positionCaseInsensitiveUTF8.

DOCSUP-50 positionCaseInsensitiveUTF8(haystack, needle)

---

docs/en/query_language/functions/string_search_functions.md

docs(multiSearchAllPositions, multiSearchAllPositionsUTF8): Full description of functions  was added

DOCSUP-178

---

docs/en/query_language/functions/other_functions.md

docs(identity()):The description of identity() function was added.

elenbaskakova-DOCSUP-191

---

docs/en/query_language/functions/string_functions.md

Short description (up to few sentences):
Add repeat() function description.

DOCSUP-190 repeat function

---

docs/en/query_language/functions/bitmap_functions.md

Short description (up to few sentences):
Add bitmapSubsetLimit() function description.

Add description of bitmapSubsetLimit()

---

docs/en/query_language/functions/other_functions.md
docs/ru/query_language/functions/other_functions.md

docs(joinGet):The description of joinGet function was added.

elenbaskakova-DOCSUP-193

---

docs/en/query_language/functions/bitmap_functions.md
docs/ru/query_language/functions/bitmap_functions.md

docs(bitmapSubsetInRange):The new description of bitmapSubsetInRange function was added.

elenbaskakova-DOSCUP-196

---

docs/en/query_language/functions/bitmap_functions.md

Short description (up to few sentences):
Add descriptions of functions bitmapMin and bitmapMax.

Add descriptions of bitmapMin & bitmapMax

---

docs/en/query_language/functions/string_functions.md

docs(concat):The new description of concat and concatAssumeInjective was edited

elenbaskakova-DOCSUP-198

---

docs/en/query_language/functions/other_functions.md

Changelog category (leave one):
- New Feature
- Bug Fix
- Improvement
- Documentation
- Other
- Non-significant (changelog entry is not needed)
Changelog entry (up to few sentences, not needed for non-significant PRs):
...
Detailed description (optional):
...

asiana21-DOCSUP-192

---

docs/en/query_language/functions/conditional_functions.md

docs(if): The new description of `if` function was edited.

elenbaskakova-DOCSUP-219

---

docs/en/query_language/functions/bit_functions.md

docs(bitTest, bitTestAny, bitTestAll):The new description of `bitTest`, `bitTestAny`, `bitTestAll` functions were added.

elenbaskakova-DOCSUP-213

---

docs/en/query_language/functions/string_functions.md

docs(trim):The new description of `trim` functions was added.

elenbaskakova-DOCSUP-649

---

docs/en/query_language/functions/array_functions.md

Add description of function arrayCompact(arr).

docs(arrayCompact): add function description

---

docs/en/query_language/functions/array_functions.md
docs/ru/query_language/functions/array_functions.md

docs(arrayDifference, arrayDistinct): The new description of `arrayDifference`, `arrayDistinct` functions were added.

elenbaskakova-DOCSUP-217

---

docs/en/query_language/functions/hash_functions.md

docs(javaHashUTF16LE):The new description of `javaHashUTF16LE` function was added.

elenbaskakova-DOCSUP-650

---

docs/en/query_language/functions/other_functions.md

Changelog category (leave one):
- New Feature
- Bug Fix
- Improvement
- Documentation
- Other
- Non-significant (changelog entry is not needed)
Changelog entry (up to few sentences, required except for Non-significant/Documentation categories):
...
Detailed description (optional):
...

asiana21-DOCSUP-216

---

docs/en/query_language/functions/geo.md

docs(geoToH3):The new description of `geoToH3` function was edited.

elenbaskakova-DOCSUP-678

---

docs/en/query_language/functions/encoding_functions.md

Changelog category (leave one):
- New Feature
- Bug Fix
- Improvement
- Documentation
- Other
- Non-significant (changelog entry is not needed)
Changelog entry (up to few sentences, required except for Non-significant/Documentation categories):
...
Detailed description (optional):
...

asiana21-DOCSUP-655

---

docs/en/query_language/functions/encoding_functions.md

Changelog category (leave one):
- New Feature
- Bug Fix
- Improvement
- Documentation
- Other
- Non-significant (changelog entry is not needed)
Changelog entry (up to few sentences, required except for Non-significant/Documentation categories):
...
Detailed description (optional):
...

asiana21-DOCSUP-656
